let NewQuestion = document.getElementById("NewQuestion");
let outPut = document.getElementById("outPut");
let question = [
  "What animal represents my mood today?",
  "What song represents my mood today?",
  "What movie represents my mood today?",
  "What story represents my mood today?",
  "What is my superhero power pose?",
  "What temperature am I today and a few words on why.",
  "What’s one thing that brings me energy and joy?",
  "What is a recent success you’ve experienced?",
  "As a kid, what did you want to be when you grew up?",
  "How is your day going on a scale of 1-5? (Everyone shows a number on their hand at once)",
  "What is a future hobby you would like to start?",
  "If you could relive any year of your life, which one would it be?",
  "What's your go-to karaoke song?",
  "​​Name one person you are close to whom you'd like to be more like, and why",
  "What do people closest to you say is your best characteristic?",
  "What part of adulting is least natural for you?",
  "What have you changed your mind about in the past 6 months?",
  "Describe your morning routine",
  "What was your favorite meal growing up?",
  "How many cities have you lived in?",
  "What is a favorite smell?",
  "What's the best thing about where you grew up?",
  "If you could travel anywhere for only one hour, where would you go?",
  "Is there a law that you'd be excited to break?",
  "What do you miss most about childhood?",
  "Name one thing that you couldn't go a week without",
  "When do you feel older than you are?",
  "When do you feel younger than you are?",
  "What's a game that you'd likely win if you played against everyone on this group?",
  "If you could get the phone number of any celebrity, whom would you choose?",
  "If you could get tickets to any event in the world (past, present, or future), what would it be?",
  "What is your favorite time of the day?",
  "Would you rather live 100 years in the past, or 100 years in the future?",
  "What's something you are thankful for today?",
  "What is something you think the group would be surprised to learn about you?",
  "What was the most unusual food you have ever eaten?",
  "If you had to move out of your country, where would you go?",
  "If you could live somewhere for one month with your expenses paid, where would you go?",
  "What language have you always wanted to learn?",
  "What Olympic sport would you love to compete in (assuming you had trained and qualified for it)?",
  "If you were on a professional sports team, what number would you wear on your uniform?",
  "What do you consider to be the coolest job/career?",
  "What's a subject/topic that you'd like to teach others about?",
  "What makes a 'good day' for you?",
  "What is your personal weather status (cloudy, foggy, sunny breaks etc)?",
  "What’s one thing that you’re really proud of?",
  "What words would you use to describe where your head is? And where your heart is?",
  "Why are you really here?",
  "What is a recent success you’ve experienced?",
  "What aspect of your job brings you the most satisfaction?",
  "What do you like best about weekends?",
  "What do you like best about vacation?",
  "What do you like best about the current season?",
  "What was your first job?",
  "Have you ever met anyone famous?",
  "If you could pick up a new skill in an instant what would it be?",
  "Who’s someone you really admire?",
  "What was your favorite band 10 years ago?",
  "What’s your earliest memory?",
  "What’s your favorite family tradition?",
  "Who had the most influence on you growing up?",
  "What was the first thing you bought with your own money?",
  "What’s something you want to do in the next year that you’ve never done before?",
  "Seen anything lately that made you smile?",
  "What’s your favorite place you’ve ever visited?",
  "What’s the best advice you’ve ever heard?",
  "How do you like your eggs?",
  "Do you have a favorite charity you wish more people knew about?",
  "Have you got any phobias you’d like to break?",
  "What is a high and a low from the day?",
  "What is one thing that you are grateful for right now?",
  "What is one thing that is currently giving you hope?",
];

console.log(question.length);
NewQuestion.onclick = function () {
  let randomQuestion = [];
  randomQuestion = question[Math.floor(Math.random() * question.length)];
  outPut.innerHTML = randomQuestion;
};
